env:
  browser: true
  es6: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
  useJSXTextNode: true
  project: ./tsconfig.json
extends:
  - plugin:@typescript-eslint/recommended
  - airbnb-base
  - plugin:promise/recommended
  - plugin:inferno/recommended
  - plugin:jsx-a11y/recommended
plugins:
  - '@typescript-eslint/eslint-plugin'
  - promise
  - inferno
  - jsx-a11y
rules:
  no-unused-vars: off
  indent: off
  '@typescript-eslint/indent':
    - error
    - 2
  '@typescript-eslint/no-extraneous-class': error
  '@typescript-eslint/restrict-plus-operands': error
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-unused-vars': off
  import/prefer-default-export: false
  import/extensions:
    - error
    - aways
    - js: never
      ts: never
      tsx: never
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .json
        - .ts
        - .tsx
      moduleDirectory:
        - node_modules
        - src
  import/parsers:
    '@typescript-eslint/parser': [.ts, .tsx]
